version: '3'

services:
  db:
    image: postgres:11.1-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
      - "../dockers/db/initdb.d:/docker-entrypoint-initdb.d"

  proxy:
    image: nginx:1.15.5-alpine
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - "../dockers/proxy/conf.d:/etc/nginx/conf.d"
#    depends_on:
#      - acesso
#      - perfil

  acesso:
    image: 'ifrn/ege.acesso'
    build:
      context: ../dockers/ege_acesso
    env_file:
      - .env
      - .acesso.env
    volumes:
      - '../apps/ege_acesso:/apps/app'

  perfil:
    image: 'ifrn/ege.django_base:1.3.1'
#    build:
#      context: ../dockers/ege_perfil
    env_file:
      - .env
    volumes:
      - '../apps/ege_perfil:/apps/app'
      - '../apps/ege_django_auth_jwt/:/libs/ege_django_auth_jwt/'
      - '../apps/ege_django_theme/:/libs/ege_django_theme/'

  processo_seletivo_administrativo:
    image: 'ifrn/ege.django_base:1.3.1'
    env_file:
      - .env
    volumes:
      - '../apps/ege_processo_seletivo_administrativo:/apps/app'

  processo_seletivo_publico:
    image: 'ifrn/ege.django_base:1.3.1'
    env_file:
      - .env
    volumes:
      - '../apps/ege_processo_seletivo_publico:/apps/app'
