version: '3'

services:
  db:
    image: postgres:11.1-alpine
    env_file:
      - ../conf/.db.env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
      - "../conf/db:/docker-entrypoint-initdb.d"

  proxy:
    image: nginx:1.15.5-alpine
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - "../conf/proxy:/etc/nginx/conf.d"
#    depends_on:
#      - acesso
#      - perfil

  acesso:
    image: 'ifrn/ege_base:1.5.2'
    env_file:
      - ../conf/.db.env
      - ../conf/.ege.env
      - ../conf/.acesso.env
      - ../conf/.acesso_ldap.env
    volumes:
      - '../apps/ege_acesso:/apps/app'
      - '../apps/ege_theme/:/libs/ege_theme/'

  perfil:
    image: 'ifrn/ege_base:1.5.2'
    env_file:
      - ../conf/.db.env
      - ../conf/.ege.env
      - ../conf/.perfil.env
    volumes:
      - '../apps/ege_perfil:/apps/app'
      - '../apps/ege_auth_jwt/:/libs/ege_auth_jwt/'
      - '../apps/ege_theme/:/libs/ege_theme/'

  seletivo:
    image: 'ifrn/ege_base:1.5.2'
    env_file:
      - ../conf/.db.env
      - ../conf/.ege.env
      - ../conf/.seletivo.env
    volumes:
      - '../apps/ege_seletivo:/apps/app'
      - '../apps/ege_auth_jwt/:/libs/ege_auth_jwt/'
      - '../apps/ege_theme/:/libs/ege_theme/'

#  selecao:
#    image: 'ifrn/ege_base:1.5.2'
#    env_file:
#      - ../conf/.db.env
#      - ../conf/.ege.env
#      - ../conf/.selecao.env
#    volumes:
#      - '../apps/ege_selecao:/apps/app'
