version: '3'

services:
  db:
    image: postgres:12.1-alpine
    env_file:
      - ../confs/db.env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
      - "./db/initdb_scripts:/docker-entrypoint-initdb.d"

  proxy:
    image: nginx:1.17.8-alpine
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - "../confs/proxy:/etc/nginx/conf.d"

  id:
    image: 'ifrn/suap_ead_base:1.5.10'
    env_file:
      - ../confs/db.env
      - ../confs/suap_ead.env
      - ../confs/id.env
      - ../confs/id_ldap.env
    volumes:
      - '../apps/id:/apps/app'
      - '../libs/:/libs/'

  dashboard:
    image: 'ifrn/suap_ead_base:1.5.10'
    env_file:
      - ../confs/db.env
      - ../confs/suap_ead.env
      - ../confs/dashboard.env
    volumes:
      - '../apps/dashboard:/apps/app'
      - '../libs/:/libs/'

  # baggins:
  #   image: 'ifrn/suap_ead_base:1.5.10'
  #   env_file:
  #     - ../confs/db.env
  #     - ../confs/suap_ead.env
  #     - ../confs/baggins.env
  #   volumes:
  #     - '../apps/suap_ead_baggins:/apps/app'
  #     - '../libs/:/libs/'

  # # c_acesso:
  # #   image: 'ifrn/suap_ead_base:1.5.10'
  # #   env_file:
  # #     - ../confs/db.env
  # #     - ../confs/suap_ead.env
  # #     - ../confs/c_acesso.env
  # #   volumes:
  # #     - '../apps/suap_ead_acesso:/apps/app'
  # #     - '../libs/:/libs/'

  # # c_perfil:
  # #   image: 'ifrn/suap_ead_base:1.5.10'
  # #   env_file:
  # #     - ../confs/db.env
  # #     - ../confs/suap_ead.env
  # #     - ../confs/c_perfil.env
  # #   volumes:
  # #     - '../apps/suap_ead_perfil:/apps/app'
  # #     - '../libs/:/libs/'
  
  # # integrador_ui:
  # #   image: 'ifrn/suap_ead_base:1.5.10'
  # #   env_file:
  # #     - ../confs/suap_ead.env
  # #     - ../confs/integrador_ui.env
  # #   volumes:
  # #     - '../apps/suap_ead_integrador_ui:/apps/app'
  # #     - '../libs/:/libs/'

  # # seletivo:
  # #   image: 'ifrn/suap_ead_base:1.5.10'
  # #   env_file:
  # #     - ../confs/db.env
  # #     - ../confs/suap_ead.env
  # #     - ../confs/seletivo.env
  # #   volumes:
  # #     - '../apps/suap_ead_seletivo:/apps/app'
  # #     - '../libs/:/libs/'

  # # selecao:
  # #   image: 'ifrn/suap_ead_base:1.5.10'
  # #   env_file:
  # #     - ../confs/db.env
  # #     - ../confs/suap_ead.env
  # #     - ../confs/selecao.env
  # #   volumes:
  # #     - '../apps/suap_ead_selecao:/apps/app'
  # #     - '../libs/:/libs/'
